config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  resources :books, only: [:show, :index]
  match '/catalog', to: 'books#index', via: 'get'
  match '/home', to: 'home#index', via: 'get'
  devise_for :users,  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  resources :users, only: %i[update destroy]
  resources :reviews, only: :create

  mount Cartify::Engine, at: '/'

  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'put'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_books = Book.latest
    @best_sellers = Book.best_sellers
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def log_out_helper
    divider = '<li class="divider" role="separator"></li>'.html_safe
    divider + li(link_to(t('button.log_out'), main_app.destroy_user_session_path, method: :delete))
  end

  def log_in_up_helper
    if user_signed_in?
      my_account =
        "<li class='dropdown'>"\
          "<a aria-expanded='false' aria-haspopup='true' class='dropdown-toggle' data-toggle='dropdown' href='#' role='button'>#{t('button.my_account')}</a>"\
          "<ul class='dropdown-menu'>" +
        li(link_to(t('button.orders'), cartify.orders_path, class: 'collapse-link')) +
        li(link_to(t('button.settings'), cartify.settings_addresses_path, class: 'collapse-link')) +
        log_out_helper +
        '</ul>'
      my_account.html_safe
    else
      li(link_to(t('button.log_in'), main_app.new_user_session_path)) +
        li(link_to(t('button.sign_up'), main_app.new_user_registration_path))
    end
  end

  def active(index)
    'active' if index.zero?
  end

  private

  def li(teg)
    "<li>#{teg}</li>".html_safe
  end
end

app/views/home/_best_sellers.haml
%h3= t('page.home.best_sellers')
.row
  - @best_sellers.each do |book|
    .col-sm-6.col-md-3
      .general-thumb-wrap
        .thumbnail.general-thumbnail
          = image_tag img_of(book), alt: book.title, class: 'img-shadow general-thumbnail-img'
          .thumb-hover
            .general-thumb-link-wrap
              = link_to book_path(book), class: 'thumb-hover-link' do
                %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
              = link_to cartify.order_items_path(order_item: {quantity: 1, product_id: book.id}), { method: :post, remote: true, class: 'thumb-hover-link' } do
                %i.fa.fa-shopping-cart.thumb-icon
      .mb-35
        .clearfix
          %p.pull-right.font-16.in-gold-500= number_to_currency(book.price)
          %p.title.mr-55= book.title
        %span.divider-sm
        %p.lead.small= authors_to_list(book)

app/views/home/_carousel.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    - @latest_books.each_index do |index|
      %li{'data-target': "#slider", 'data-slide-to': "{index}", class: "#{active(index)}"}
  .carousel-inner{role: "listbox"}
    - @latest_books.each_with_index do |fresh_book, index|
      .item{class: "#{active(index)}"}
        .row
          .col-sm-5
            .general-img-wrap
              = image_tag carousel_img(fresh_book), alt: fresh_book.title, class: 'img-shadow general-thumbnail-img'
          .col-sm-7
            .mb-60
              %h1= fresh_book.title
              %p.lead= markdown(fresh_book.description)
              %p.lead.small= authors_to_list(fresh_book)
              .general-align
                = button_to t('button.by_now'), cartify.order_items_path(order_item: {quantity: 1, product_id: fresh_book.id}), { method: :post, remote: true, class: 'btn btn-primary', disabled: !fresh_book.active }
  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only= t('page.home.carusel.prev')
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only= t('page.home.carusel.next')

app/views/home/index.haml
%main.container
  = render 'carousel'
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('page.home.greeting')
    .mb-res-50
      %p= t('page.home.text')
    = link_to t('button.get_started'), catalog_path ,class: 'button btn btn-default'
  .mb-35
    = render 'best_sellers'