config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  resources :books, only: [:show, :index]
  match '/catalog', to: 'books#index', via: 'get'
  match '/home', to: 'home#index', via: 'get'
  devise_for :users,  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  resources :users, only: %i[update destroy]
  resources :reviews, only: :create

  mount Cartify::Engine, at: '/'

  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'put'
end

app/views/settings/_edit_email.haml
%p.in-gold-500.font-18.mb-25= t('settings.e-mail')
= form_for(resource, as: resource_name, url: user_path(resource), html: { method: :put, class: 'general-form-md email' }) do |f|
  .form-group.mb-35
    = f.label :email, t('settings.enter_e-mail'), class: 'control-label input-label'
    = f.email_field :email, autofocus: true, autocomplete: "off", class: 'form-control', placeholder: t('settings.enter_your_e-mail')
    = f.hidden_field :update_email, value: true
  .general-text-align
    = f.submit t('settings.save'), class: 'btn btn-default mb-35'

app/views/settings/_edit_password.haml
%p.in-gold-500.font-18.mb-25= t('settings.password')
= form_for(resource, as: resource_name, url: user_path(resource), html: { method: :put, class: 'general-form-md divider-lg-bottom pb-25'}) do |f|
  = devise_error_messages!
  .form-group.mb-30
    = f.label :current_password, t('settings.old_password'), class: "control-label input-label"
    = f.password_field :current_password, class: "form-control", autocomplete: "off", placeholder: t('settings.old_password')
  .form-group.mb-30
    = f.label :password, t('settings.new_password'), class: "control-label input-label"
    = f.password_field :password, class: "form-control", autofocus: true, autocomplete: "off", placeholder: t('settings.new_password')
  .form-group.mb-40
    = f.label :password_confirmation, t('settings.confirm_password'), class: "control-label input-label"
    = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: t('settings.confirm_password')
  .general-text-align
    = f.submit t('settings.save'), class: 'btn btn-default mb-10'

app/views/settings/_remove_account.haml
%p.in-gold-500.font-18.mb-25= t('settings.remove_account')
.general-settings-btn
  = button_to t('settings.please_remove_account'), registration_path(resource_name), class: 'btn btn-default mb-20', data: { confirm: "Are you sure?" }, method: :delete
.form-group.checkbox.general-settings-checkbox
  %label.checkbox-label#remove_account
    %input.checkbox-input{type: "checkbox", hidden: "true"}
    %span.checkbox-icon
      %i.fa.fa-check
    %span.checkbox-text= t('settings.im_agree_lost_all_data')